### ISSUE TITLE
default clusterRole ineffecient  for vcluster serviceaccount

### ISSUE THREAD

**Issue by jbarfield** [loft-sh/vcluster-plugins#42]
I had to update the clusterrole RBAC permissions in order for this plugin to work.

k3s version 1.6.29 on k8s 1.26.5 (kubespray).

Yaml like so:

```
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
```
